#!/usr/bin/with-contenv bash

# shellcheck disable=SC2086
# shellcheck shell=bash

umask 022
cd /app
sqraper_command="torify php sqraper.php"
echo "-> Starting Sqraper <-"
exec s6-setuidgid abc $sqraper_command
